<?php
declare(strict_types=1);

/**
 * Plateformes de formation en ligne et sélection initiale de cours (français et anglais uniquement).
 * Les liens ont été vérifiés lors de la constitution du catalogue ; Coursera et FUN MOOC sont ensuite
 * tenus à jour automatiquement par leurs connecteurs (bin/sync-trainings.php), les autres plateformes
 * par import de fichier depuis l'administration.
 *
 * Cours : [titre, chemin ou URL, langue, organisme, durée, certificat (gratuit|payant|badge|aucun|variable), niveau, compétences]
 */
return [
    'platforms' => [
        'coursera' => [
            'name' => 'Coursera', 'url' => 'https://www.coursera.org', 'color' => '#0056D2', 'languages' => 'fr,en', 'pricing' => 'freemium', 'connector' => 'coursera',
            'tagline' => 'Les cours des grandes universités et entreprises mondiales',
            'pricing_note' => 'De nombreux cours peuvent être suivis gratuitement en mode « audit ». Le certificat est payant, et une aide financière peut être demandée directement sur le cours.',
            'certificate_note' => 'Certificat partageable délivré avec l\'université ou l\'entreprise partenaire (Google, IBM, Meta, Microsoft…).',
            'description' => "Coursera réunit les cours de plus de 300 universités et entreprises. Les programmes « Professional Certificate » préparent à un métier précis (analyste de données, support informatique, gestion de projet…) et sont très reconnus des recruteurs.\nLa majorité des cours sont en anglais, avec des sous-titres, mais une sélection existe en français.",
            'strengths' => "Certificats signés par des marques reconnues (Google, IBM, Microsoft, universités)\nProgrammes complets orientés métier, accessibles sans prérequis\nAide financière disponible sur demande pour le certificat",
            'tips' => "Clique sur « S'inscrire » puis cherche l'option d'audit pour accéder gratuitement au contenu.\nPour le certificat, fais une demande d'aide financière : la réponse arrive en général en deux semaines.\nAjoute le lien de ton certificat sur Tremplin : il est vérifiable par les recruteurs.",
        ],
        'openclassrooms' => [
            'name' => 'OpenClassrooms', 'url' => 'https://openclassrooms.com/fr', 'color' => '#7451EB', 'languages' => 'fr,en', 'pricing' => 'freemium', 'connector' => 'manual',
            'tagline' => 'La plateforme francophone des cours en ligne orientés métier',
            'pricing_note' => 'De nombreux cours en accès libre. Les parcours diplômants avec mentor sont payants (des financements existent).',
            'certificate_note' => 'Les conditions d\'obtention d\'un certificat de réussite sont indiquées sur chaque cours ; les parcours diplômants délivrent un diplôme reconnu.',
            'description' => "OpenClassrooms est une école en ligne française. Ses cours, courts et pratiques, couvrent le numérique, la data, la gestion de projet, le marketing et la gestion d'entreprise, avec des exercices à faire soi-même.\nC'est souvent le meilleur point de départ pour apprendre en français, à son rythme.",
            'strengths' => "Cours en français, pensés pour les débutants\nExercices pratiques et quiz pour valider chaque partie\nParcours diplômants avec mentor pour aller plus loin",
            'tips' => "Commence par un cours « Initiez-vous » ou « Découvrez » : ils ne demandent aucun prérequis.\nFais tous les exercices : ce sont eux qui te serviront d'exemples en entretien.\nUne fois le cours terminé, ajoute-le à ton profil Tremplin.",
        ],
        'udemy' => [
            'name' => 'Udemy', 'url' => 'https://www.udemy.com', 'color' => '#A435F0', 'languages' => 'fr,en', 'pricing' => 'payant', 'connector' => 'manual',
            'tagline' => 'Des milliers de cours pratiques créés par des professionnels',
            'pricing_note' => 'Cours payants à l\'unité, régulièrement proposés en promotion. Quelques cours sont gratuits. L\'accès est à vie une fois le cours acheté.',
            'certificate_note' => 'Certificat de réussite Udemy à la fin du cours : il n\'a pas valeur de diplôme mais prouve ta démarche.',
            'description' => "Udemy est une place de marché où des formateurs indépendants publient leurs cours vidéo. On y trouve des formations très pratiques sur les logiciels (Excel, Power BI, AutoCAD…) et la préparation aux certifications (CCNA, Security+).\nLa qualité varie selon le formateur : fie-toi aux avis et au nombre d'inscrits.",
            'strengths' => "Très large choix, y compris en français\nCours pratiques, souvent orientés logiciel ou certification\nAccès à vie et à ton rythme",
            'tips' => "Attends une période de promotion : les prix baissent très souvent.\nVérifie la note, le nombre d'avis et la date de mise à jour avant d'acheter.\nPrivilégie les cours qui préparent à une certification reconnue.",
        ],
        'edx' => [
            'name' => 'edX', 'url' => 'https://www.edx.org', 'color' => '#02262B', 'languages' => 'en,fr', 'pricing' => 'freemium', 'connector' => 'manual',
            'tagline' => 'Les cours de Harvard, du MIT et des grandes universités',
            'pricing_note' => 'Beaucoup de cours sont accessibles gratuitement (audit). Le certificat vérifié est payant.',
            'certificate_note' => 'Certificat vérifié délivré par l\'université ou l\'institution partenaire.',
            'description' => "Fondée par Harvard et le MIT, edX propose des cours universitaires exigeants. Le célèbre CS50 de Harvard, des cours d'anglais professionnel, de comptabilité ou de gestion de projet y sont disponibles.\nLa plupart des cours sont en anglais.",
            'strengths' => "Contenus universitaires de très haut niveau\nCours d'anglais professionnel reconnus\nAccès gratuit au contenu de nombreux cours",
            'tips' => "Choisis l'option gratuite (audit) pour commencer, puis le certificat si le cours te convient.\nLes cours de Harvard et des grandes écoles sont un vrai plus sur un CV.",
        ],
        'fun-mooc' => [
            'name' => 'FUN MOOC', 'url' => 'https://www.fun-mooc.fr', 'color' => '#E2001A', 'languages' => 'fr,en', 'pricing' => 'gratuit', 'connector' => 'fun-mooc',
            'tagline' => 'Les MOOC des universités et grandes écoles françaises',
            'pricing_note' => 'La grande majorité des cours sont gratuits. Certains proposent un certificat payant.',
            'certificate_note' => 'Attestation de suivi ou certificat selon le cours ; les modalités sont indiquées sur chaque session.',
            'description' => "France Université Numérique publie les MOOC des universités et écoles françaises : informatique, gestion, santé, environnement, agriculture…\nLes cours fonctionnent par sessions avec des dates d'inscription : la prochaine session est indiquée sur Tremplin quand elle est connue.",
            'strengths' => "Cours gratuits en français, conçus par des universités\nThèmes rares ailleurs : santé, environnement, agriculture, droit\nSessions encadrées avec forums",
            'tips' => "Inscris-toi avant la date limite de la session : les inscriptions ferment.\nSuis le rythme hebdomadaire proposé, c'est la clé pour aller au bout.",
        ],
        'microsoft-learn' => [
            'name' => 'Microsoft Learn', 'url' => 'https://learn.microsoft.com/fr-fr/training/', 'color' => '#0078D4', 'languages' => 'fr,en', 'pricing' => 'gratuit', 'connector' => 'manual',
            'tagline' => 'Les parcours officiels et gratuits de Microsoft',
            'pricing_note' => 'Tous les parcours d\'apprentissage sont gratuits. Les examens de certification Microsoft sont payants.',
            'certificate_note' => 'Trophées et badges gratuits sur ton profil Microsoft Learn ; certifications officielles via examen.',
            'description' => "Microsoft Learn propose, en français, les parcours officiels pour maîtriser Power BI, Excel, Azure ou la sécurité. Chaque parcours prépare à une certification Microsoft reconnue par les entreprises.",
            'strengths' => "Gratuit et en français\nContenu officiel, à jour des dernières versions\nPrépare directement aux certifications Microsoft",
            'tips' => "Crée un profil Microsoft Learn pour suivre ta progression et partager tes trophées.\nEnchaîne les parcours qui préparent à la même certification (par exemple PL-300 pour Power BI).",
        ],
        'freecodecamp' => [
            'name' => 'freeCodeCamp', 'url' => 'https://www.freecodecamp.org', 'color' => '#0A0A23', 'languages' => 'en', 'pricing' => 'gratuit', 'connector' => 'manual',
            'tagline' => 'Apprendre à coder gratuitement, par la pratique',
            'pricing_note' => 'Entièrement gratuit, y compris les certifications.',
            'certificate_note' => 'Certification gratuite obtenue en réalisant des projets, avec un lien vérifiable.',
            'description' => "freeCodeCamp est une association à but non lucratif. Ses certifications (développement web, JavaScript, Python, bases de données, analyse de données) s'obtiennent en codant de vrais projets, directement dans le navigateur.",
            'strengths' => "100 % gratuit, certifications comprises\nApprentissage par projets, idéal pour un portfolio\nCommunauté mondiale très active",
            'tips' => "Code un peu chaque jour : la régularité compte plus que la durée.\nPublie tes projets sur GitHub et ajoute le lien de ta certification sur Tremplin.",
        ],
        'cisco-netacad' => [
            'name' => 'Cisco Networking Academy', 'url' => 'https://www.netacad.com', 'color' => '#1BA0D7', 'languages' => 'en,fr', 'pricing' => 'gratuit', 'connector' => 'manual',
            'tagline' => 'Réseaux, cybersécurité et informatique avec Cisco',
            'pricing_note' => 'De nombreux cours gratuits en ligne ; certains cursus sont proposés par des écoles partenaires.',
            'certificate_note' => 'Badge numérique et attestation à la fin des cours ; ils préparent aux certifications Cisco (CCNA) et CompTIA.',
            'description' => "La Cisco Networking Academy forme aux réseaux, à la cybersécurité, à l'informatique et à la programmation. Ses cours gratuits sont une excellente préparation aux certifications recherchées par les opérateurs télécoms et les services informatiques.",
            'strengths' => "Cours gratuits avec badge numérique\nPréparation reconnue au CCNA\nSimulateur réseau Packet Tracer inclus",
            'tips' => "Commence par « Networking Basics » ou « Introduction to Cybersecurity ».\nUtilise Packet Tracer pour t'entraîner : c'est l'outil des épreuves Cisco.",
        ],
    ],

    'courses' => [
        'openclassrooms' => [
            ['Maîtrisez les fondamentaux d\'Excel', '/fr/courses/7168336-maitrisez-les-fondamentaux-d-excel', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'debutant', 'Excel avancé, Pack Office'],
            ['Perfectionnez-vous sur Excel', '/fr/courses/7139456-perfectionnez-vous-sur-excel', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'intermediaire', 'Excel avancé'],
            ['Master the Fundamentals of Excel', '/fr/courses/7723761-master-the-fundamentals-of-excel', 'en', 'OpenClassrooms', 'À ton rythme', 'variable', 'debutant', 'Excel avancé'],
            ['Apprenez les bases du langage Python', '/fr/courses/7168871-apprenez-les-bases-du-langage-python', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'debutant', 'Python'],
            ['Initiez-vous à Python pour l\'analyse de données', '/fr/courses/6204541-initiez-vous-a-python-pour-l-analyse-de-donnees', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'debutant', 'Python, Analyse de données'],
            ['Requêtez une base de données avec SQL', '/fr/courses/7818671-requetez-une-base-de-donnees-avec-sql', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'debutant', 'SQL'],
            ['Réalisez des dashboards avec Power BI', '/fr/courses/7110891-realisez-des-dashboards-avec-power-bi', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'debutant', 'Power BI, Analyse de données'],
            ['Nettoyez et analysez votre jeu de données', '/fr/courses/7410486-nettoyez-et-analysez-votre-jeu-de-donnees', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'intermediaire', 'Analyse de données, Python'],
            ['Développez votre culture des données', '/fr/courses/7869811-developpez-votre-culture-des-donnees', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'debutant', 'Analyse de données'],
            ['Créez votre site web avec HTML5 et CSS3', '/fr/courses/1603881-creez-votre-site-web-avec-html5-et-css3', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'debutant', 'HTML / CSS'],
            ['Apprenez à programmer avec JavaScript', '/fr/courses/7696886-apprenez-a-programmer-avec-javascript', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'debutant', 'JavaScript'],
            ['Débutez avec React', '/fr/courses/8710331-debutez-avec-react', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'intermediaire', 'JavaScript'],
            ['Concevez votre site web avec PHP et MySQL', '/fr/courses/918836-concevez-votre-site-web-avec-php-et-mysql', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'debutant', 'PHP, SQL'],
            ['Gérez du code avec Git et GitHub', '/fr/courses/7162856-gerez-du-code-avec-git-et-github', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'debutant', 'Git'],
            ['Concevez votre réseau TCP/IP', '/fr/courses/6944606-concevez-votre-reseau-tcp-ip', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'debutant', 'Réseaux informatiques'],
            ['Simulez le schéma de votre réseau avec Cisco Packet Tracer', '/fr/courses/7192261-simulez-le-schema-de-votre-reseau-avec-cisco-packet-tracer', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'intermediaire', 'Réseaux informatiques'],
            ['Initiez-vous à Linux', '/fr/courses/7170491-initiez-vous-a-linux', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'debutant', 'Support informatique'],
            ['Montez un PC', '/fr/courses/7210326-montez-un-pc', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'debutant', 'Support informatique'],
            ['Prenez en main Windows Server', '/fr/courses/2356306-prenez-en-main-windows-server', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'intermediaire', 'Support informatique, Réseaux informatiques'],
            ['Initiez-vous à la comptabilité', '/fr/courses/4801106-initiez-vous-a-la-comptabilite', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'debutant', 'Comptabilité générale'],
            ['Réalisez les opérations courantes de comptabilité', '/fr/courses/4940566-realisez-les-operations-courantes-de-comptabilite', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'debutant', 'Comptabilité générale'],
            ['Réalisez une comptabilité de fin d\'exercice', '/fr/courses/5010961-realisez-une-comptabilite-de-fin-d-exercice', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'intermediaire', 'Comptabilité générale, Analyse financière'],
            ['Adoptez une démarche qualité, hygiène, sécurité, environnement', '/fr/courses/5258771-adoptez-une-demarche-qualite-hygiene-securite-environnement', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'debutant', 'HSE'],
            ['Décryptez une fiche de paie', '/fr/courses/4667641-decryptez-une-fiche-de-paie', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'debutant', 'Gestion des ressources humaines'],
            ['Élaborez un plan de recrutement', '/fr/courses/4539151-elaborez-un-plan-de-recrutement', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'debutant', 'Gestion des ressources humaines'],
            ['Découvrez les métiers des ressources humaines', '/fr/courses/8558161-decouvrez-les-metiers-des-ressources-humaines', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'debutant', 'Gestion des ressources humaines'],
            ['Initiez-vous au marketing digital', '/fr/courses/3013816-initiez-vous-au-marketing-digital', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'debutant', 'Marketing digital'],
            ['Augmentez votre trafic grâce au référencement naturel (SEO)', '/fr/courses/5561431-augmentez-votre-trafic-grace-au-referencement-naturel-seo', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'intermediaire', 'Marketing digital'],
            ['Lancez une campagne de publicité avec Google Ads', '/fr/courses/7396991-lancez-une-campagne-de-publicite-avec-google-ads', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'debutant', 'Marketing digital'],
            ['Découvrez le métier de community manager', '/fr/courses/6144321-decouvrez-le-metier-de-community-manager', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'debutant', 'Gestion des réseaux sociaux'],
            ['Construisez une stratégie social media', '/fr/courses/8274066-construisez-une-strategie-social-media', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'intermediaire', 'Gestion des réseaux sociaux, Marketing digital'],
            ['Lancez une campagne Facebook Ads', '/fr/courses/3829076-lancez-une-campagne-facebook-ads', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'debutant', 'Gestion des réseaux sociaux'],
            ['Gérez vos relations client grâce au CRM', '/fr/courses/7778566-gerez-vos-relations-client-grace-au-crm', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'debutant', 'Gestion de la relation client, Techniques de vente'],
            ['Réalisez une étude de marché', '/fr/courses/6067991-realisez-une-etude-de-marche', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'debutant', 'Marketing digital, Analyse de données'],
            ['Initiez-vous à la gestion de projet', '/fr/courses/8744811-initiez-vous-a-la-gestion-de-projet', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'debutant', 'Gestion de projet'],
            ['Initiez-vous à la gestion de projet agile', '/fr/courses/4507926-initiez-vous-a-la-gestion-de-projet-agile', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'debutant', 'Gestion de projet'],
            ['Gérez votre projet avec une équipe Scrum', '/fr/courses/4511226-gerez-votre-projet-avec-une-equipe-scrum', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'intermediaire', 'Gestion de projet'],
            ['Analysez les risques de votre projet', '/fr/courses/5774866-analysez-les-risques-de-votre-projet', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'intermediaire', 'Gestion de projet'],
            ['Découvrez les fondamentaux du BIM', '/fr/courses/5228291-decouvrez-les-fondamentaux-du-bim', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'debutant', 'Génie civil, AutoCAD'],
            ['Utilisez ChatGPT pour améliorer votre productivité', '/fr/courses/8204091-utilisez-chatgpt-pour-ameliorer-votre-productivite', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'debutant', 'Sens de l\'organisation, Pack Office'],
            ['Développez votre personal branding', '/fr/courses/4698761-developpez-votre-personal-branding', 'fr', 'OpenClassrooms', 'À ton rythme', 'variable', 'debutant', 'Communication'],
        ],
        'udemy' => [
            ['The Complete Python Bootcamp From Zero to Hero in Python', '/course/complete-python-bootcamp/', 'en', 'Jose Portilla', 'Environ 22 h de vidéo', 'payant', 'debutant', 'Python'],
            ['The Complete SQL Bootcamp: Go from Zero to Hero', '/course/the-complete-sql-bootcamp/', 'en', 'Jose Portilla', 'À ton rythme', 'payant', 'debutant', 'SQL'],
            ['The Complete SQL & Power BI Bootcamp: Become a Data Analyst', '/course/the-complete-sql-power-bi-bootcamp-become-a-data-analyst/', 'en', 'Udemy', 'À ton rythme', 'payant', 'debutant', 'Analyse de données, SQL, Power BI'],
            ['Microsoft Power BI - Formation Complète - Débutant à Expert', '/course/microsoft-power-bi-formation-complete-debutant-a-expert/', 'fr', 'Udemy', 'À ton rythme', 'payant', 'debutant', 'Power BI'],
            ['Formation complète Microsoft Excel pour débutant - Niveau I', '/course/formation-microsoft-excel-pour-debutant-niveau-i/', 'fr', 'Udemy', 'À ton rythme', 'payant', 'debutant', 'Excel avancé, Pack Office'],
            ['Formation Complete QGis 3.x : Devenez un Spécialiste SIG', '/course/formation-complete-qgis-3x-devenez-un-specialiste-sig/', 'fr', 'Udemy', 'À ton rythme', 'payant', 'debutant', 'SIG / Cartographie'],
            ['Symfony 7 - Débutant à expert - Projet concret avec un blog', '/course/symfony-7-debutant-a-expert-projet-concret-avec-un-blog/', 'fr', 'Udemy', 'À ton rythme', 'payant', 'intermediaire', 'PHP'],
            ['Cisco CCNA 200-301 – The Complete Guide to Getting Certified', '/course/ccna-complete/', 'en', 'Neil Anderson', 'À ton rythme', 'payant', 'intermediaire', 'Réseaux informatiques'],
            ['Network Fundamentals, Wireshark & Packet Tracer', '/course/networking-network-fundamentals-wireshark-packet-tracer/', 'en', 'Udemy', 'À ton rythme', 'payant', 'debutant', 'Réseaux informatiques'],
            ['Python for Cybersecurity', '/course/python-for-cybersecurity/', 'en', 'Udemy', 'À ton rythme', 'payant', 'debutant', 'Cybersécurité, Python'],
            ['Graphic Design Foundations: From Zero to Pro', '/course/graphic-design-foundations-from-zero-to-pro/', 'en', 'Udemy', 'À ton rythme', 'payant', 'debutant', 'Création graphique'],
        ],
        'edx' => [
            ['Introduction to Project Management', '/learn/project-management/university-of-adelaide-introduction-to-project-management', 'en', 'University of Adelaide', 'À ton rythme', 'payant', 'debutant', 'Gestion de projet'],
            ['Agile and Scrum Fundamentals', '/learn/agile/ibm-agile-and-scrum-fundamentals', 'en', 'IBM', 'À ton rythme', 'payant', 'debutant', 'Gestion de projet'],
            ['Upper-Intermediate English: Business and Industry', '/learn/english/universitat-politecnica-de-valencia-upper-intermediate-english-business-and-industry', 'en', 'Universitat Politècnica de València', 'À ton rythme', 'payant', 'intermediaire', 'Anglais'],
            ['English Grammar and Style', '/learn/grammar/the-university-of-queensland-english-grammar-and-style', 'en', 'The University of Queensland', 'À ton rythme', 'payant', 'intermediaire', 'Anglais, Rédaction'],
            ['Accounting Fundamentals', '/learn/economics-finance/the-london-school-of-economics-and-political-science-accounting-fundamentals', 'en', 'London School of Economics', 'À ton rythme', 'payant', 'debutant', 'Comptabilité générale'],
            ['Excel for Everyone: Core Foundations', '/learn/excel/university-of-british-columbia-excel-for-everyone-core-foundations', 'en', 'University of British Columbia', 'À ton rythme', 'payant', 'debutant', 'Excel avancé'],
            ['Excel for Everyone: Data Analysis Fundamentals', '/learn/excel/university-of-british-columbia-excel-for-everyone-data-analysis-fundamentals', 'en', 'University of British Columbia', 'À ton rythme', 'payant', 'intermediaire', 'Analyse de données, Excel avancé'],
            ['CS50\'s Introduction to Cybersecurity', '/learn/cybersecurity/harvard-university-cs50-s-introduction-to-cybersecurity', 'en', 'Harvard University', 'À ton rythme', 'payant', 'debutant', 'Cybersécurité'],
            ['Cybersecurity Basics: Tools and Cyberattacks', '/learn/cybersecurity/ibm-cybersecurity-basics-tools-and-cyberattacks', 'en', 'IBM', 'À ton rythme', 'payant', 'debutant', 'Cybersécurité'],
            ['CS50\'s Introduction to Computer Science', '/learn/computer-science/harvard-university-cs50-s-introduction-to-computer-science', 'en', 'Harvard University', 'À ton rythme', 'payant', 'debutant', 'Python, SQL'],
            ['Supply Chain Management: A Decision-Making Framework', '/learn/supply-chain-management/universite-catholique-de-louvain-supply-chain-management-a-decision-making-framework', 'en', 'Université catholique de Louvain', 'À ton rythme', 'payant', 'intermediaire', 'Logistique, Gestion des stocks'],
            ['Digital Marketing Strategy', '/learn/digital-marketing/the-university-of-edinburgh-digital-marketing-strategy', 'en', 'The University of Edinburgh', 'À ton rythme', 'payant', 'intermediaire', 'Marketing digital'],
        ],
        'microsoft-learn' => [
            ['Bien démarrer avec l\'analytique de données Microsoft', '/fr-fr/training/paths/data-analytics-microsoft/', 'fr', 'Microsoft', 'Quelques heures', 'badge', 'debutant', 'Power BI, Analyse de données'],
            ['Préparer les données pour l\'analyse avec Power BI', '/fr-fr/training/paths/prepare-data-power-bi/', 'fr', 'Microsoft', 'Quelques heures', 'badge', 'intermediaire', 'Power BI'],
            ['Créer et utiliser des rapports d\'analytique avec Power BI', '/fr-fr/training/paths/power-bi-effective/', 'fr', 'Microsoft', 'Quelques heures', 'badge', 'intermediaire', 'Power BI'],
            ['Notions de base d\'Azure : décrire les concepts du cloud', '/fr-fr/training/paths/microsoft-azure-fundamentals-describe-cloud-concepts/', 'fr', 'Microsoft', 'Environ 1 h', 'badge', 'debutant', 'Support informatique'],
            ['Décrire les concepts de sécurité, de conformité et d\'identité', '/fr-fr/training/paths/describe-concepts-of-security-compliance-identity/', 'fr', 'Microsoft', 'Environ 1 h', 'badge', 'debutant', 'Cybersécurité'],
        ],
        'freecodecamp' => [
            ['Responsive Web Design', '/learn/2022/responsive-web-design/', 'en', 'freeCodeCamp', 'Environ 300 h', 'gratuit', 'debutant', 'HTML / CSS'],
            ['JavaScript Algorithms and Data Structures', '/learn/javascript-algorithms-and-data-structures-v8/', 'en', 'freeCodeCamp', 'Environ 300 h', 'gratuit', 'debutant', 'JavaScript'],
            ['Scientific Computing with Python', '/learn/scientific-computing-with-python/', 'en', 'freeCodeCamp', 'Environ 300 h', 'gratuit', 'debutant', 'Python'],
            ['Relational Database', '/learn/relational-database/', 'en', 'freeCodeCamp', 'Environ 300 h', 'gratuit', 'debutant', 'SQL, Git'],
            ['Data Analysis with Python', '/learn/data-analysis-with-python/', 'en', 'freeCodeCamp', 'Environ 300 h', 'gratuit', 'intermediaire', 'Analyse de données, Python'],
        ],
        'cisco-netacad' => [
            ['Introduction to Cybersecurity', '/courses/introduction-to-cybersecurity', 'en', 'Cisco', 'Environ 6 h', 'badge', 'debutant', 'Cybersécurité'],
            ['Networking Basics', '/courses/networking-basics', 'en', 'Cisco', 'Environ 22 h', 'badge', 'debutant', 'Réseaux informatiques'],
            ['Python Essentials 1', '/courses/python-essentials-1', 'en', 'Cisco / OpenEDG Python Institute', 'Environ 30 h', 'badge', 'debutant', 'Python'],
            ['IT Essentials', '/courses/it-essentials', 'en', 'Cisco', 'Environ 70 h', 'badge', 'debutant', 'Support informatique'],
        ],
    ],
];
