<?php
/*
 * Référentiel Diplômes & Équivalences Tremplin v1.1 (proposition NEAM, statut brouillon : à valider par les experts).
 * Échelle commune N0 à N6 du cahier des charges. Un diplôme étranger est rattaché au niveau correspondant ;
 * en cas de doute il est marqué « à vérifier » plutôt que classé par défaut.
 * Champs : intitulé, niveau Tremplin, pays ou zone, reconnaissance, synonymes (pour la reconnaissance dans les CV).
 */
return [
    'levels' => [
        0 => ['N0', 'Sans diplôme', '—'],
        1 => ['N1', 'Fin du premier cycle secondaire', 'BEPC, CAP'],
        2 => ['N2', 'Baccalauréat', 'Bac général, technique, professionnel'],
        3 => ['N3', 'Bac+2', 'BTS, DUT, DTS'],
        4 => ['N4', 'Bac+3', 'Licence LMD, licence professionnelle'],
        5 => ['N5', 'Bac+5', 'Master, diplôme d\'ingénieur'],
        6 => ['N6', 'Bac+8', 'Doctorat'],
    ],
    'degrees' => [
        // [intitulé, niveau, pays/zone, reconnaissance, synonymes, à vérifier]
        ['BEPC (Brevet d\'études du premier cycle)', 1, 'Gabon', 'État', 'bepc,brevet d etudes du premier cycle', false],
        ['CAP (Certificat d\'aptitude professionnelle)', 1, 'Gabon / France', 'État', 'cap,certificat d aptitude professionnelle', false],
        ['Brevet des collèges (DNB)', 1, 'France', 'État', 'dnb,brevet des colleges,brevet', false],
        ['Baccalauréat général', 2, 'Gabon / France', 'État', 'bac general,baccalaureat general,bac a,bac c,bac d', false],
        ['Baccalauréat technique', 2, 'Gabon', 'État', 'bac technique,baccalaureat technique,bac g,bac f,bac e', false],
        ['Baccalauréat professionnel', 2, 'Gabon / France', 'État', 'bac pro,baccalaureat professionnel', false],
        ['Baccalauréat technologique', 2, 'France', 'État', 'bac techno,baccalaureat technologique,stmg,sti2d', false],
        ['Diplôme de fin d\'études secondaires (étranger)', 2, 'Étranger', 'À vérifier', 'high school diploma,a level,a levels,gce a level', true],
        ['BTS (Brevet de technicien supérieur)', 3, 'Gabon / France', 'État', 'bts,brevet de technicien superieur', false],
        ['DUT (Diplôme universitaire de technologie)', 3, 'Gabon / France', 'État', 'dut,diplome universitaire de technologie', false],
        ['DTS (Diplôme de technicien supérieur)', 3, 'Gabon', 'État', 'dts,diplome de technicien superieur', false],
        ['DEUG (Diplôme d\'études universitaires générales)', 3, 'Gabon / France', 'État', 'deug', false],
        ['HND (Higher National Diploma)', 3, 'Pays anglophones', 'À vérifier', 'hnd,higher national diploma', true],
        ['Licence (LMD)', 4, 'Gabon / CEMAC / France', 'État, CAMES', 'licence,licence lmd,licence 3,l3', false],
        ['Licence professionnelle', 4, 'Gabon / CEMAC / France', 'État, CAMES', 'licence pro,licence professionnelle', false],
        ['Bachelor', 4, 'International', 'À vérifier', 'bachelor,bachelor s degree,bsc,ba', true],
        ['BUT (Bachelor universitaire de technologie)', 4, 'France', 'État', 'but,bachelor universitaire de technologie', false],
        ['Diplôme d\'État d\'infirmier', 4, 'Gabon / France', 'État (diplôme réglementé)', 'diplome d etat d infirmier,ide,infirmier d etat', false],
        ['Diplôme d\'État de sage-femme', 4, 'Gabon / France', 'État (diplôme réglementé)', 'diplome d etat de sage femme,sage femme d etat', false],
        ['Maîtrise (Bac+4)', 4, 'Gabon / France', 'État', 'maitrise,master 1,m1', false],
        ['Master', 5, 'Gabon / CEMAC / France', 'État, CAMES', 'master,master 2,m2,dess,dea', false],
        ['Diplôme d\'ingénieur', 5, 'Gabon / France', 'État', 'diplome d ingenieur,ingenieur', false],
        ['MBA', 5, 'International', 'À vérifier', 'mba,master of business administration', true],
        ['Master\'s degree (étranger)', 5, 'International', 'À vérifier', 'master s degree,msc,ma', true],
        ['Doctorat', 6, 'Gabon / CEMAC / France', 'État, CAMES', 'doctorat,phd,these', false],
    ],
    // Domaines d'études : comparés aux domaines habituels de chaque fiche métier
    'fields' => [
        'informatique' => ['Informatique et numérique', 'informatique,developpement,genie logiciel,systemes d information,reseaux,data,miage,programmation,cybersecurite,numerique'],
        'telecoms' => ['Télécommunications', 'telecom,telecommunications,reseaux et telecoms'],
        'electronique' => ['Électronique', 'electronique'],
        'communication' => ['Communication et journalisme', 'communication,journalisme,medias,information et communication'],
        'marketing' => ['Marketing', 'marketing,mercatique'],
        'commerce' => ['Commerce et vente', 'commerce,vente,action commerciale,negociation,management des unites commerciales,muc,ndrc,technico commercial'],
        'finance' => ['Finance, banque, assurance', 'finance,banque,assurance,monnaie,credit,microfinance'],
        'gestion' => ['Gestion et management', 'gestion,management,administration des entreprises,sciences de gestion,aes,gea'],
        'comptabilite' => ['Comptabilité et audit', 'comptabilite,cca,audit,controle de gestion,dcg,dscg,expertise comptable'],
        'economie' => ['Économie', 'economie,econometrie,sciences economiques'],
        'statistique' => ['Statistique', 'statistique,statistiques,econometrie,actuariat'],
        'mathematiques' => ['Mathématiques', 'mathematiques,maths,actuariat,mathematiques appliquees'],
        'ressources humaines' => ['Ressources humaines', 'ressources humaines,grh,rh,gestion du personnel'],
        'droit' => ['Droit', 'droit,juridique,sciences juridiques,droit des affaires,droit prive,droit public'],
        'secretariat' => ['Secrétariat et assistanat', 'secretariat,assistanat,assistant de direction,assistant manager,bureautique,support a l action manageriale'],
        'logistique' => ['Transport et logistique', 'logistique,transport,supply chain,transit,douane'],
        'geosciences' => ['Géosciences, mines et pétrole', 'geologie,geosciences,mines,petrole,geophysique,hydrocarbures,genie petrolier'],
        'electrotechnique' => ['Électrotechnique et électricité', 'electrotechnique,electricite,genie electrique,electromecanique'],
        'mecanique' => ['Mécanique et maintenance', 'mecanique,maintenance,genie mecanique,productique,electromecanique'],
        'metallurgie' => ['Métallurgie et soudage', 'metallurgie,soudage,chaudronnerie'],
        'chimie' => ['Chimie et génie des procédés', 'chimie,genie chimique,genie des procedes,petrochimie'],
        'genie des procedes' => ['Génie des procédés', 'genie des procedes,genie chimique,raffinage'],
        'energie' => ['Énergie', 'energie,energies renouvelables,genie energetique,solaire'],
        'hse' => ['Hygiène, sécurité, environnement', 'hse,qhse,hygiene securite environnement,securite industrielle,qualite'],
        'genie civil' => ['Génie civil et BTP', 'genie civil,btp,batiment,travaux publics,construction,topographie'],
        'architecture' => ['Architecture', 'architecture,urbanisme'],
        'geographie' => ['Géographie et géomatique', 'geographie,geomatique,sig,cartographie,teledetection'],
        'foresterie' => ['Foresterie et eaux et forêts', 'foresterie,eaux et forets,sylviculture,forestier'],
        'environnement' => ['Environnement et biodiversité', 'environnement,biodiversite,ecologie,sciences de l environnement,conservation'],
        'bois' => ['Bois et transformation du bois', 'bois,industrie du bois,menuiserie,ebenisterie,scierie'],
        'agronomie' => ['Agronomie et agriculture', 'agronomie,agriculture,production vegetale,phytotechnie,agroeconomie'],
        'agroalimentaire' => ['Agroalimentaire', 'agroalimentaire,industries alimentaires,technologie alimentaire'],
        'elevage' => ['Élevage et productions animales', 'elevage,zootechnie,productions animales'],
        'aquaculture' => ['Aquaculture et halieutique', 'aquaculture,halieutique,peche,pisciculture'],
        'biologie' => ['Biologie', 'biologie,biochimie,biotechnologies'],
        'sante' => ['Santé', 'sante,soins infirmiers,medecine,pharmacie,sage femme,biologie medicale,imagerie medicale,paramedical'],
        'hotellerie' => ['Hôtellerie et restauration', 'hotellerie,restauration,hotel'],
        'cuisine' => ['Cuisine', 'cuisine,arts culinaires,restauration'],
        'tourisme' => ['Tourisme', 'tourisme,ecotourisme'],
        'education' => ['Sciences de l\'éducation', 'education,sciences de l education,enseignement,pedagogie,ens,ecole normale'],
        'sciences sociales' => ['Sciences sociales', 'sociologie,anthropologie,psychologie,sciences sociales,sciences politiques,developpement'],
        'travail social' => ['Travail social', 'travail social,assistant social,action sociale'],
        'psychologie' => ['Psychologie', 'psychologie'],
        'langues' => ['Langues et traduction', 'langues,lea,llce,traduction,anglais,interpretariat'],
        'lettres' => ['Lettres', 'lettres,lettres modernes,litterature'],
    ],
];
